apiVersion: v1
kind: Service
metadata:
  name: esphome-fleet-headless
  labels:
    app.kubernetes.io/name: esphome-fleet
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: esphome-fleet

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esphome-fleet
  labels:
    app.kubernetes.io/name: esphome-fleet
spec:
  serviceName: esphome-fleet-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: esphome-fleet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esphome-fleet
    spec:
      containers:
        - name: esphome-fleet
          image: ghcr.io/weirded/esphome-dist-client:1.7.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: esphome-fleet-secret
                  key: server_url
                  optional: false
            - name: SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: esphome-fleet-secret
                  key: server_token
                  optional: false
            - name: MAX_PARALELL_JOBS
              value: "4"
            - name: ESPHOME_SEED_VERSION
              value: "2026.7.4"
          volumeMounts:
            - name: esphome-fleet-worker
              mountPath: /esphome-versions
  volumeClaimTemplates:
    - metadata:
        name: esphome-fleet-worker
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi